import { iocContainer } from "../../../../Earth.Shared/ts/ioc/ioc";
import { ProxyTypes } from "./types.g";
import { WaterService as Ocean_WaterService } from "../ocean/services/water-service";
import { TricksService as Dolphin_TricksService } from "../dolphin/services/tricks-service";
import { OceanSurfaceBroadcast as Ocean_OceanSurfaceBroadcast } from "../ocean/broadcasts/ocean-surface-broadcast";
import { DolphinCoordinateMapper as Ocean_MapToContractDolphinCoordinate } from "../ocean/mappers/requests/dolphin-coordinate-mapper";
import { HurricaneCoordinateMapper as Ocean_MapToContractHurricaneCoordinate } from "../ocean/mappers/requests/hurricane-coordinate-mapper";
import { DolphinCoordinatePutMapper as Ocean_MapToContractDolphinCoordinatePut } from "../ocean/mappers/requests/dolphin-coordinate-put-mapper";
import { HurricaneCoordinatePutMapper as Ocean_MapToContractHurricaneCoordinatePut } from "../ocean/mappers/requests/hurricane-coordinate-put-mapper";
import { DolphinCoordinateMapper as Ocean_MapFromContractDolphinCoordinate } from "../ocean/mappers/results/dolphin-coordinate-mapper";
import { HurricaneCoordinateMapper as Ocean_MapFromContractHurricaneCoordinate } from "../ocean/mappers/results/hurricane-coordinate-mapper";
import { DolphinCoordinatePutMapper as Ocean_MapFromContractDolphinCoordinatePut } from "../ocean/mappers/results/dolphin-coordinate-put-mapper";
import { HurricaneCoordinatePutMapper as Ocean_MapFromContractHurricaneCoordinatePut } from "../ocean/mappers/results/hurricane-coordinate-put-mapper";
import { DolphinCoordinateMapper as Dolphin_MapToContractDolphinCoordinate } from "../dolphin/mappers/requests/dolphin-coordinate-mapper";
import { DolphinCoordinateMapper as Dolphin_MapFromContractDolphinCoordinate } from "../dolphin/mappers/results/dolphin-coordinate-mapper";

iocContainer.addSingletonForLazyConstruction(ProxyTypes.Ocean_IWaterService, () => new Ocean_WaterService());
iocContainer.addSingletonForLazyConstruction(ProxyTypes.Dolphin_ITricksService, () => new Dolphin_TricksService());
iocContainer.addSingletonForLazyConstruction(ProxyTypes.Ocean_IOceanSurfaceBroadcast, () => new Ocean_OceanSurfaceBroadcast());
iocContainer.addSingletonForLazyConstruction(ProxyTypes.Ocean_MapToContractDolphinCoordinate, () => new Ocean_MapToContractDolphinCoordinate());
iocContainer.addSingletonForLazyConstruction(ProxyTypes.Ocean_MapToContractHurricaneCoordinate, () => new Ocean_MapToContractHurricaneCoordinate());
iocContainer.addSingletonForLazyConstruction(ProxyTypes.Ocean_MapToContractDolphinCoordinatePut, () => new Ocean_MapToContractDolphinCoordinatePut());
iocContainer.addSingletonForLazyConstruction(ProxyTypes.Ocean_MapToContractHurricaneCoordinatePut, () => new Ocean_MapToContractHurricaneCoordinatePut());
iocContainer.addSingletonForLazyConstruction(ProxyTypes.Ocean_MapFromContractDolphinCoordinate, () => new Ocean_MapFromContractDolphinCoordinate());
iocContainer.addSingletonForLazyConstruction(ProxyTypes.Ocean_MapFromContractHurricaneCoordinate, () => new Ocean_MapFromContractHurricaneCoordinate());
iocContainer.addSingletonForLazyConstruction(ProxyTypes.Ocean_MapFromContractDolphinCoordinatePut, () => new Ocean_MapFromContractDolphinCoordinatePut());
iocContainer.addSingletonForLazyConstruction(ProxyTypes.Ocean_MapFromContractHurricaneCoordinatePut, () => new Ocean_MapFromContractHurricaneCoordinatePut());
iocContainer.addSingletonForLazyConstruction(ProxyTypes.Dolphin_MapToContractDolphinCoordinate, () => new Dolphin_MapToContractDolphinCoordinate());
iocContainer.addSingletonForLazyConstruction(ProxyTypes.Dolphin_MapFromContractDolphinCoordinate, () => new Dolphin_MapFromContractDolphinCoordinate());
